name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    #deno deploy token store in secrets: DENO_DEPLOY_TOKEN
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: cbv-api # the name of the project on Deno Deploy
          entrypoint: mod.ts # the entrypoint to deploy
